name: Bootstrap Templated Repository

on:
  create

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - run: echo "Updating repository"
